//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.31 at 12:13:36 PM ALMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bekzat.kz/springbootsoapservice/user", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package kz.bekzat.springbootsoapservice.user;
